#
# This file is part of the fastimage npm package. Copyright (C) 2015 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

---
exclude_paths:
  - coverage/**/*
  - examples/**/*
  - docs/**/*
  - test/**/*
engines:
  eslint:
    enabled: true
  env:
    node: true
    mocha: true
    es6: true